---

    -   name: Download Minio
        get_url:
            url: https://dl.min.io/server/minio/release/linux-amd64/minio
            dest: /usr/local/bin/minio
        # when: 
        #     - os_check.stdout | regex_search("Ubuntu 18")


    -   name: Ensure group "minio" exists
        group:
            name: minio
            state: present

    -   name: Add the user 'minio'
        user:
            name: minio
            shell: /sbin/nologin
            groups: minio
            append: yes

    -   name: Give Permissions
        file:
            path: /usr/local/bin/minio
            owner: minio
            group: minio
            mode: '0755'

    -   name: Create Minio Directory
        file:
            path: /usr/local/share/minio
            state: directory
            owner: minio
            group: minio

    -   name: Create Minio Directory
        file:
            path: /usr/local/share/minio
            state: directory
            recurse: yes
            owner: minio
            group: minio

    -   name: Create Minio Config Directory
        file:
            path: /etc/minio
            state: directory
            recurse: yes
            owner: minio
            group: minio
    
    -   name: Set the default config
        become: true
        template:
            src: "minio.config.j2"
            dest: "/etc/default/minio"

    -   name: Download Minio.service
        get_url:
            url: https://raw.githubusercontent.com/minio/minio-service/master/linux-systemd/minio.service
            dest: /etc/systemd/system/minio.service

    -   name: Enable and start minio service
        systemd:
            state: started
            daemon_reload: yes
            enabled: yes
            name: minio

    